config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  ActiveAdmin.routes(self)


  get 'users/:user_id/profil', to: 'pages#profil', as: :profil

  get 'dashboard', to: 'pages#dashboard'
  get 'uikit', to: 'pages#uikit'
  resources :contacts, only: [ :new, :create ]

  resources :locations, only: [ :new, :create, :edit, :update, :destroy ]
  resources :boardgames, only: [ :new, :create, :edit, :update, :destroy ]

  resources :gamenights do
    resources :participations, only: [ :create ]
  end

  resources :participations, only: [ :edit, :update, :destroy ]
end

app/models/gamenight.rb
class Gamenight < ApplicationRecord
  belongs_to :location
  belongs_to :boardgame
  has_many :participations, dependent: :destroy

  validates :date, presence: true
  validates :start_time, presence: true
  validates :location, presence: true
  validates :boardgame, presence: true
end

app/controllers/gamenights_controller.rb
require 'will_paginate/array'

class GamenightsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_gamenight, only: [:show, :edit, :update, :destroy]
  before_action :send_cancelation, only: :destroy


  def index
    @gamenight_geocoded = policy_scope(Location).geocoded.map do |location|
      location.gamenights.filter do |gamenight|
        futur_gamenights.include?(gamenight)
      end
    end.flatten.sort_by { |gamenight| gamenight.date }

    if params[:query].present?
      boardgames = policy_scope(Boardgame).search_by_name_and_category(params[:query])
      @gamenight_geocoded = @gamenight_geocoded.filter do |gamenight|
        boardgames.include?(gamenight.boardgame)
      end
    end

    @gamenights_index = @gamenight_geocoded.paginate(page: params[:page], per_page: 4)


    @markers = @gamenight_geocoded.map do |gamenight|
      {
        lat: gamenight.location.latitude,
        lng: gamenight.location.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { gamenight: gamenight }),
        image_url: helpers.asset_url('avatar.png')
      }

    end
  end

  def show
    @boardgame = @gamenight.boardgame
    @location = @gamenight.location
    @user = @boardgame.user
    @participations = @gamenight.participations
  end

  def new
    @gamenight = Gamenight.new
    authorize @gamenight

    @locations_user = current_user.locations
    @boardgames_user = current_user.boardgames
  end

  def create
    @gamenight = Gamenight.new(gamenight_params)
    authorize @gamenight

    if @gamenight.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @locations_user = current_user.locations
    @boardgames_user = current_user.boardgames
  end

  def update
    if @gamenight.update(gamenight_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @gamenight.destroy

    redirect_to dashboard_path
  end

  private

  def send_cancelation
    GamenightMailer.send_cancelation_notice(@gamenight)
  end

  def futur_gamenights
    gamenights = policy_scope(Gamenight)
    gamenights_display = gamenights.select do |gamenight|

      number_of_players = gamenight.boardgame.players_max > gamenight.participations.size
      futur_date = gamenight.date > Time.now.to_date
      today_date = gamenight.date == Time.now.to_date
      futur_time = gamenight.start_time.hour - 2 >= Time.now.hour

      gamenight if (futur_date || (today_date && futur_time)) && number_of_players
    end
    # trie des gamenights futures de la plus proche à la plus loingtaine
    return gamenights_display
  end

  def find_gamenight
    @gamenight = policy_scope(Gamenight).find(params[:id])
    authorize @gamenight
  end

  def gamenight_params
    params.require(:gamenight).permit(:date, :start_time, :end_time, :description, :boardgame_id, :location_id)
  end
end

app/views/gamenights/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2 form">
      <h1 class="title">Creer ta soirée </h1>
      <%= simple_form_for(gamenight) do |f| %>
        <%= f.input :date, as: :date, html5: true %>
        <%= f.input :start_time, :label => "Heure de début", input_html: { class: "select2" } %>
        <%= f.input :end_time, :label => "Heure de fin", input_html: { class: "select2" } %>
        <%= f.input :description, as: :text %>
        <%= f.input :location_id, :collection => @locations_user, :label => "Adresse", input_html: { class: "select2" } %>
        <%= f.input :boardgame_id, :collection => @boardgames_user, :label => "Jeux", input_html: { class: "select2" }%>
        <% if gamenight.location_id.blank? %>
          <%= f.submit "Créer ma soirée", class: "button-form"%>
        <% else %>
          <%= f.submit "Modifier ma soirée", class: "button-form"%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/gamenights/_info_window.html.erb
<div class="container">
  <div>
    <p class="pop-title"><%= gamenight.boardgame.name %></p>
    <p class="pop-time"><%= gamenight.date.strftime("Le %d-%m-%Y") %> <%= gamenight.start_time.strftime("à %H:%M") %></p>
    <p class="pop-user">Chez <%= gamenight.boardgame.user.username %></p>
    <%= link_to gamenight_path(gamenight) do %>
      <i class="fas fa-eye"></i>
    <% end %>
  </div>
</div>

app/views/gamenights/edit.html.erb
<%= render 'form', gamenight: @gamenight %>

app/views/gamenights/index.html.erb
<div class="row mt-4 mb-4">
  <div class="col-md-8 offset-2">
    <h1 class="title text-center">Toutes les soirées à venir 🎲 </h1>
    <p style="color:#ea526f;"class="text-center"> Rejoins ta future gamenight! </p>
  </div>
</div>
<div class="row">
  <div class="col-md-6 pr-0">
    <div class="cards">
    <% @gamenights_index.each do |gamenight| %>
      <%= link_to gamenight_path(gamenight) do %>
        <div class="card">
          <% gamenight_image = gamenight.boardgame.photo.attached? ? cl_image_path(gamenight.boardgame.photo.key) : image_path("game-card.png") %>
          <div class="card-image" style="background-image: url(<%= gamenight_image %>)">
            <p class="category-tag"><%= gamenight.boardgame.category %></p>
            <% if gamenight.boardgame.user.photo.attached? %>
            <%= cl_image_tag gamenight.boardgame.user.photo.key, crop: :fill, class: "avatar-card" %>
            <% else %>
            <%= image_tag "avatar.jpg", crop: :fill, class: "avatar-card" %>
            <% end %>
          </div>
          <div class="card-text">
            <h2><%= gamenight.boardgame.name %></h2>
            <span class="date"><%= gamenight.date.strftime("Le %d-%m-%Y") %></span>
            <p><%= gamenight.description %></p>
          </div>
          <div class="card-stats">
            <div class="stat">
              <div class="value"><i class="fas fa-user-friends"></i></div>
              <div class="type"><%= gamenight.boardgame.players_max %></div>
            </div>
            <div class="stat2">
              <div class="value"><i class="fas fa-clock"></i></div>
              <div class="type"><%= gamenight.start_time.strftime("%H:%M") %></div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  <%= will_paginate @gamenights_index, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>

  <div class="col-md-6 pl-0">
    <div
      id="map"
      style="
      width: 100%;
      flex-grow: 1;
      position: sticky;
      top: 0;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  </div>

</div>

app/views/gamenights/new.html.erb
<%= render 'form', gamenight: @gamenight %>

app/views/gamenights/show.html.erb
<div class="container mt-5 mb-4">
  <div class="row row-design position-relative mb-5">
    <div class="card-big col-4">
      <div class="card-img">
        <% if @boardgame.photo.attached? %>
        <%= cl_image_tag @boardgame.photo.key, class: "gamenight-show-image" %>
        <% else %>
        <%= image_tag "game-card.png", class: "gamenight-show-image" %>
        <% end %>
        <% if @user.photo.attached?  %>
          <a href="<%= profil_path(@user) %>"><%= cl_image_tag @user.photo.key, class: "avatar3", id: "show-gamenight" %></a>
        <% else %>
          <a href="<%= profil_path(@user) %>"><%= image_tag "avatar.jpg", class: "avatar3", id: "show-gamenight" %></a>
        <% end %>
     </div>
    </div>
    <div class="col-8">
      <div class="games-specs row justify-content-between align-items-center">
        <h2 class="gamename"><%= @boardgame.name %></h2>
        <h6 class="username"><%= @user.username.capitalize%>'s GameNight</h6>
        <h6 class="joueurs"><%= @boardgame.players_min %> - <%= @boardgame.players_max %> joueurs</h6>
      </div>
      <div class="row gamenight-elements">
        <div class="description col-8">
          <p>Description : <br><%= @boardgame.description.capitalize %></p>
        </div>
        <div class="row align-items-end col-4">
          <div class="button-participation offset-3"><% if (@gamenight.date > Time.now.to_date) && (@boardgame.players_max > @participations.size)  %>
            <%= link_to 'Participer', gamenight_participations_path(@gamenight), method: :post, data: { confirm: "Participation prise en compte"} %>
              <% elsif @gamenight.date < Time.now.to_date %>
                <p><strong>Participations fermées</strong></p>
              <% elsif (@gamenight.date == Time.now.to_date) && (@gamenight.start_time.hour - 2 >= Time.now.hour) && (@boardgame.players_max > @participations.size) %>
                <%= link_to 'Participer', gamenight_participations_path(@gamenight), method: :post, data: { confirm: "Participation prise en compte"} %>
              <% else %>
                <p><strong>Participations fermées</strong></p>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-3 mb-3">
  <div class="row position-relative">
    <div class= "participants-tile">
      <div class="mr-5">
        <h3>Participants déjà inscrits :</h3>
      </div>
      <% if @participations.length == 0 %>
      <div class="mr-5">
        <h3>Aucun</h3>
      </div>
      <% else %>
        <% @participations.each do |participation| %>
          <div class="mr-5 participants-profil">
            <% if participation.user.photo.attached? %>
              <%= link_to profil_path(participation.user) do %>
              <div>
                <%= cl_image_tag participation.user.photo.key, crop: :fill, class: "avatar1" %>
              </div>
              <% end %>
            <% else %>
              <%= link_to profil_path(participation.user) do %>
              <div>
                <%= image_tag "avatar.jpg", crop: :fill, class: "avatar1" %>
              </div>
              <% end %>
            <% end %>
            <% if participation.user.username %>
            <div>
              <%= participation.user.username %>
            </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>