config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  ActiveAdmin.routes(self)


  get 'users/:user_id/profil', to: 'pages#profil', as: :profil

  get 'dashboard', to: 'pages#dashboard'
  get 'uikit', to: 'pages#uikit'
  resources :contacts, only: [ :new, :create ]

  resources :locations, only: [ :new, :create, :edit, :update, :destroy ]
  resources :boardgames, only: [ :new, :create, :edit, :update, :destroy ]

  resources :gamenights do
    resources :participations, only: [ :create ]
  end

  resources :participations, only: [ :edit, :update, :destroy ]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>
   <%= link_to "Contact", new_contact_path, class: "text-white" %> - Mentions légales - CGU - CGV - Protection des données
  </div>
  <div class="footer-copyright">
    <%= image_tag "ludinlogo.png", style: "height: 30px", alt: "logo" %>
      © 2020 Ludin
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "ludinlogo.png" %>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Soirées", gamenights_path, class: "nav-link", :style=>'color: white;' %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag "avatar.jpg", crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link", :style=>'color: white;' %>
        </li>
        <li>
          <%= link_to "Créer un compte", new_user_registration_path, class: "nav-link", :style=>'color: white;' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>