config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  ActiveAdmin.routes(self)


  get 'users/:user_id/profil', to: 'pages#profil', as: :profil

  get 'dashboard', to: 'pages#dashboard'
  get 'uikit', to: 'pages#uikit'
  resources :contacts, only: [ :new, :create ]

  resources :locations, only: [ :new, :create, :edit, :update, :destroy ]
  resources :boardgames, only: [ :new, :create, :edit, :update, :destroy ]

  resources :gamenights do
    resources :participations, only: [ :create ]
  end

  resources :participations, only: [ :edit, :update, :destroy ]
end

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url('https://images.radio-canada.ca/q_auto,w_1250/v1/ici-info/16x9/jeu-de-societe-famille-amis-noel.jpg');">
  <div class="container">
    <div class="d-flex flex-column">
      <div>
        <h1> Rejoins une gamenight, augmente tes stats, <br>et soit le meilleur joueur de plateau!</h1>
        <%= simple_form_for :search, url: gamenights_path, method: :get do |f| %>
          <div class="search-form-control search-for-banner form-group">
            <input class="form-control longform string required" type="text" name="query" id="search_query" placeholder="Cherche par nom ou catégorie de jeu" />
            <button name="button" type="submit" class="btn btn-flat">
              <i class="fas fa-search" ></i>
            </button>
          </div>
        <% end %>
      </div>
<!--       <div class="border d-flex flex-column align-items-center">
        <div><p class="text-center text-white">X gamers sont actifs sur LUD-IN</p></div>
        <div><p class="text-center text-white">Il y a actuellement X gamenights à venir</p></div>
      </div> -->
    </div>
  </div>
</div>



<div class="container-home">
<div class="bg-light page-section">
  <div class="container text-center mt-3 mb-3">
    <div class="concept">
    <h1 class="hello">Le Concept Ludin ♟</h1>
    <p class="body text-ludin"> Ludin à été crée dans le but de se faire rencontrer les ludophiles les plus prés de chez toi ! Marre de ne pas pouvoir tester ou jouer à ses jeux car il manque toujours Pierre ou Paul ? Postez une annonce, et rencontrer vos futurs partenaires de jeux !
  </p>
  </div>
  </div>
  </div>

  <div class="coupebanner"></div>

<div class="container-home">
<div class="bg-light page-section">
  <div class="container text-center mt-3 mb-3">
    <div class="concept">
    <h1 class="hello">Comment ça marche ❓ 🎲</h1>
    <p class="body faq"> ❓- Tu viens d'acheter Zombicide mais tes copines n'aiment pas ? <br>✅ Mets une annonce pour trouver d'autres passionés de ce jeu pour jouer avec toi ! </p>
    <p class="body faq"> ❓- Tu n'as pas de jeux de sociétés et tu aimerais en découvrir auprés de joueurs agguéris ? <br>✅ Fais une recherche par nom si tu as une idée particuliére, ou bien par ville dans l'onglet Gamenight ! </p>
  </div>
  </div>
  </div>

 <div class="coupebanner"></div>


<section class="bg-light page-section" id="team">
    <div class="container team">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">La LudinTeam 💻</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="team-member">
            <%= image_tag "kevin.jpeg", class: "mx-auto rounded-circle" %>
            <h4>Kevin </h4>
            <p class="text-muted">Porteur de projet</p>
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="https://github.com/Kraynaud">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              </li>
              <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/kevin-raynaud/">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="team-member">
            <%= image_tag "bertrand.jpeg", class: "mx-auto rounded-circle" %>
            <h4>Bertrand</h4>
            <p class="text-muted">Developpeur fullstack</p>
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="https://github.com/Bertrand-Bichat">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/bertrand-bichat/">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="team-member">
            <%= image_tag "sebastien.jpeg", class: "mx-auto rounded-circle" %>
            <h4>Seb</h4>
            <p class="text-muted">Front Developpeur</p>
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="https://github.com/sebmcreations">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/sebmcreations/">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="team-member">
            <%= image_tag "eve.jpeg", class: "mx-auto rounded-circle" %>
            <h4>Eve </h4>
            <p class="text-muted">Developpeur fullstack</p>
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="https://github.com/eveuuh">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="www.linkedin.com/in/evejourdan">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <p class="large text-muted">N'hesitez pas à nous contacter via nos reseaux pour d'éventuelles collaborations!</p>
          <div class="mb-5 mt-4">
            <a href="mailto:ludin.fun@gmail.com" target="_blank" class="button-contact">Contactez-nous</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  </div>
</div>

app/views/pages/profil.html.erb
<div class="container">
  <% if @user.username.blank? %>
    <h1 class="mt-4 mb-4 title">Profil d'un inconnu</h1>
  <% else %>
    <h1 class="mt-4 mb-4 title">Profil de <%= @user.username %></h1>
  <% end %>
  <div class="row">

    <!-- Profil card -->

    <div class="col-md-4 tagcloud profil">
      <div class="dashboard-profil-tile">
        <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, crop: :fill, class: "avatar-profil" %>
        <% else %>
        <%= image_tag "avatar.jpg", crop: :fill, class: "avatar-profil" %>
        <% end %>
        <div class="user-details mt-2">
          <div class="specs">
            <% if @user.calculation_global_rating.nan? %>
              <h5><em>(nouveau membre)</em></h5>
            <% elsif @user.has_a_global_rating? %>
              <div class="profil-review-rating text-center">
                <% case @user.calculation_global_rating.round %>
                <% when 5 %>
                  <div class="user-scoring">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                  </div>
                <% when 4 %>
                  <div class="user-scoring">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                <% when 3 %>
                  <div class="user-scoring">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                <% when 2 %>
                    <div class="user-scoring">
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                    </div>
                <% when 1 %>
                    <div class="user-scoring">
                      <i class="fas fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                    </div>
                <% end %>
              </div>
            <% else %>
              <h3>(nouveau membre)</h3>
            <% end %>
          </div>
        </div>
        <div class="profil-links mt-5">
          <%= link_to 'Messages', "#", class: "link" %>
        </div>
      </div>
    </div>
<!-- end -->

<!-- Soirées -->
    <div class="col-md-8">
      <div id="profil-list">
        <h2 class="title">Ses soirées à venir</h2>
        <ul class="list-unstyled">
          <% if @user_futur_gamenights.length >= 1 %>
            <% @gamenights_profil.each do |gamenight| %>
              <li class="profil-gamenight-card">
                <div class="gamenight-upvote text-center" id="profil-gamenight-upvote">
                  <i class="fas fa-user-friends"></i>
                  <p><%= gamenight.boardgame.players_max %></p>
                </div>
                <% if gamenight.boardgame.photo.attached? %>
                <%= cl_image_tag gamenight.boardgame.photo.key, height: 150, width: 250, crop: :limit, class: "gamenight-image img-rounded" %>
                <% else %>
                <%= image_tag "game-card.png", height: 150, width: 150, crop: :limit, class: "gamenight-image img-rounded" %>
                <% end %>
                <div class="gamenight-description">
                  <h3><%= gamenight.boardgame.name %></h3>
                  <p><i class="far fa-calendar-alt"> </i> <%= gamenight.date.strftime("%d-%m-%Y") %> <%= gamenight.start_time.strftime("à %H:%M") %></p>
                  <p><i class="fas fa-map-pin"></i> <%= gamenight.location.address %></p>
                </div>
                <div>
                  <ul class="list-inline gamenight-controls">
                    <li>
                      <%= link_to gamenight_path(gamenight) do %>
                      <i class="fas fa-eye"></i>
                      <% end %>
                    </li>
                  </ul>
                </div>
              </li>
            <% end %>
            <%= will_paginate @gamenights_profil, param_name: 'gamenights_page', renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
          <% else %>
            <li class="nill-tile-bb pt-5"><p>Rien de prévu pour l'instant</p></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<!-- end -->

<!-- Commentaires -->
  <div class="row">
    <div class="col-md-12 mt-4 mb-4">
      <div class="reviews-tile">
        <h2 class="title">
          <div class="ml-3">
            Commentaires sur ses soirées
          </div>
        </h2>
        <ul class="list-unstyled">
          <% @reviews_profil.each do |participation| %>
            <li class="profil-gamenight-bb mb-1">
              <div class="profil-review-upvote text-center border-right">
                <% if participation.user.photo.attached? %>
                <%= cl_image_tag participation.user.photo.key, crop: :fill, class: "avatar1" %>
                <% else %>
                <%= image_tag "avatar.jpg", crop: :fill, class: "avatar1" %>
                <% end %>
                <%= link_to participation.user.username, profil_path(participation.user) %>
              </div>
              <div class="profil-review-gamenight text-center border-right">
                <div>
                  <p><%= participation.gamenight.date.strftime("%d-%m-%Y") %></p>
                </div>
                <div>
                  <p><%= participation.gamenight.boardgame.name %></p>
                </div>
              </div>
              <div class="profil-review-description text-center w-100">
                <p><%= participation.description %></p>
              </div>
              <div class="profil-review-rating text-center">
                <% case participation.rating %>
                <% when 5 %>
                  <div class="user-scoring">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                  </div>
                <% when 4 %>
                  <div class="user-scoring">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                <% when 3 %>
                  <div class="user-scoring">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                    <i class="far fa-star"></i>
                  </div>
                <% when 2 %>
                    <div class="user-scoring">
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                    </div>
                <% when 1 %>
                    <div class="user-scoring">
                      <i class="fas fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                    </div>
                <% end %>
              </div>
            </li>
          <% end %>
          <%= will_paginate @reviews_profil, param_name: 'reviews_page', renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
        </ul>
      </div>
    </div>
  </div>
<!-- end -->
</div>